# Generated by Django 4.0.5 on 2022-06-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rutCliente', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='RUT')),
                ('nombreCliente', models.CharField(max_length=20, verbose_name='NOMBRE CLIENTE')),
                ('apellidoCliente', models.CharField(max_length=20, verbose_name='APELLIDO CLIENTE')),
                ('telefonoCliente', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID PRODUCTO')),
                ('nombreProducto', models.CharField(max_length=50, verbose_name='NOMBRE PRODUCTO')),
                ('precioProducto', models.IntegerField(verbose_name='PRECIO PRODUCTO')),
                ('descripcionProducto', models.TextField(max_length=50, verbose_name='DESCRIPCION DEL PRODUCTO')),
            ],
        ),
    ]
