# Generated by Django 4.0.5 on 2022-07-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='correoCliente',
            field=models.CharField(default='CORREO', max_length=20, verbose_name='CORREO CLIENTE'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccionCliente',
            field=models.CharField(default='DIRECCION', max_length=20, verbose_name='DIRECCION CLIENTE'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefonoCliente',
            field=models.IntegerField(verbose_name='TELEFONO CLIENTE'),
        ),
    ]
