# Generated by Django 4.0.5 on 2022-07-01 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cliente_correocliente_cliente_direccioncliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correoCliente',
            field=models.CharField(default='CORREO', max_length=50, verbose_name='CORREO CLIENTE'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccionCliente',
            field=models.CharField(default='DIRECCION', max_length=50, verbose_name='DIRECCION CLIENTE'),
        ),
    ]
